#pragma once
#include <array>
#include <string>

class Catalogs
{
public:
	enum Index : int
	{
		NMS = 0, //NON_MODIFYING_SEQUENCE_OPERATIONS = 0,
		MS,		//MODIFYING_SEQUENCE_OPERATIONS,
		PAR,	//PARTITIONING_OPERATIONS,
		SORT,	//SORTING_OPERATIONS,
		BSOSR,	//BINARY_SEARCH_OPERATIONS_ON_SORTED_RANGES,
		OOSR,	//OTHER_OPERATIONS_ON_SORTED_RANGES,
		SOSR,	//SET_OPERATIONS_ON_SORTED_RANGES,
		HEAP,	//HEAP_OPERATIONS,
		MINMAX, //MINIMUM_MAXIMUM_OPERATIONS,
		COMP,	//COMPARISON_OPERATIONS,
		PER,	//PERMUTATION_OPERATIONS,
		NUM,	//NUMERIC_OPERATIONS,
		OOUM,	//OPERATIONS_ON_UNINITIALIZED_MEMORY,
		END		//CATALOGS_END
	};
	std::array<std::string, Index::END> mNames;
};

