#pragma once

enum class Catalogs
{
	NON_MODIFYING_SEQUENCE_OPERATIONS,
	MODIFYING_SEQUENCE_OPERATIONS,
	PARTITIONING_OPERATIONS,
	SORTING_OPERATIONS,
	BINARY_SEARCH_OPERATIONS_ON_SORTED_RANGES,
	OTHER_OPERATIONS_ON_SORTED_RANGES,
	SET_OPERATIONS_ON_SORTED_RANGES,
	HEAP_OPERATIONS,
	MINIMUM_MAXIMUM_OPERATIONS,
	COMPARISON_OPERATIONS,
	PERMUTATION_OPERATIONS,
	NUMERIC_OPERATIONS,
	OPERATIONS_ON_UNINITIALIZED_MEMORY
};

class Manager
{

};

